#!/bin/sh

if [ -z "${LE_CONTACT_EMAIL:=}" ]; then
    echo "Environment variable LE_CONTACT_EMAIL not set"
    echo "No email will be associated with the registration request"
else
    CONTACT_EMAIL="$LE_CONTACT_EMAIL"
fi

if [ -n "${LE_STAGING:=}" ] && [ "$LE_STAGING" != "0" ]; then
    CA="https://acme-staging-v02.api.letsencrypt.org/directory"
    CA_TERMS="https://acme-staging-v02.api.letsencrypt.org/terms"
fi

# Backward compatibility, see entrypoint.sh
if [ -n "${LE_ACCOUNTDIR:=}" ]; then
    ACCOUNTDIR="$LE_ACCOUNTDIR"
fi
if [ -n "${LE_CERTDIR:=}" ]; then
    CERTDIR="$LE_CERTDIR"
fi

API=2
